import { GameMode } from "@/types/game";

export const SECRET_WORDS = [
  // Objetos cotidianos
  "Geladeira", "Guarda-chuva", "Mochila", "Colchão", "Ventilador", "Escova de dente",
  "Garrafa térmica", "Travesseiro", "Relógio", "Óculos", "Carteira", "Chave",
  "Caneta", "Tesoura", "Espelho", "Vela", "Corda", "Régua", "Mapa", "Bússola",
  // Animais
  "Elefante", "Golfinho", "Pinguim", "Cobra", "Águia", "Tartaruga", "Polvo",
  "Camelo", "Gorila", "Flamingo", "Urso polar", "Tubarão", "Panda", "Leão",
  "Tigre", "Baleia", "Coruja", "Raposa", "Lobo", "Macaco",
  // Alimentos
  "Pizza", "Sorvete", "Chocolate", "Hambúrguer", "Sushi", "Pastel", "Coxinha",
  "Macarrão", "Queijo", "Mel", "Pipoca", "Tapioca", "Bolo", "Brigadeiro",
  "Mousse", "Churros", "Croissant", "Ramen", "Lasanha", "Paçoca",
  // Tecnologia
  "Computador", "Celular", "Fone de ouvido", "Câmera", "Drone", "Impressora",
  "Teclado", "Mouse", "Tablet", "Microfone", "Alto-falante", "Carregador",
  // Natureza
  "Vulcão", "Cachoeira", "Deserto", "Iceberg", "Floresta", "Coral",
  "Furacão", "Aurora boreal", "Gêiser", "Caverna", "Penhasco", "Lago",
  "Nevoeiro", "Avalanche", "Redemoinho", "Relâmpago", "Arco-íris",
  // Transporte
  "Submarino", "Foguete", "Helicóptero", "Navio", "Trem bala", "Teleférico",
  "Moto aquática", "Planador", "Zeppelin", "Bicicleta", "Trator", "Ambulância",
  // Lugares
  "Biblioteca", "Castelo", "Farol", "Pirâmide", "Iglu", "Bunker",
  "Observatório", "Labirinto", "Cemitério", "Aquário", "Museu", "Circo",
  // Esportes e lazer
  "Paraquedas", "Skate", "Escalada", "Mergulho", "Arco e flecha", "Xadrez",
  "Boliche", "Golfe", "Surfe", "Parkour",
  // Profissões/objetos temáticos
  "Bisturi", "Martelo", "Pincel", "Violino", "Microfone", "Troféu",
  "Diploma", "Passaporte", "Bilhete", "Moeda",
  // Conceitos / abstratos simples
  "Segredo", "Sonho", "Memória", "Silêncio", "Sombra", "Eco",
];

export const LOCATIONS_WITH_ROLES: Record<string, string[]> = {
  Hospital: ["Cirurgião", "Enfermeiro", "Paciente", "Médico emergencista", "Anestesista", "Recepcionista", "Farmacêutico", "Psiquiatra"],
  Aeroporto: ["Piloto", "Comissário de bordo", "Passageiro", "Controlador de voo", "Agente de segurança", "Mecânico de aeronave", "Despachante", "Fiscal de alfândega"],
  "Escola de Magia": ["Diretor", "Professor de feitiços", "Aluno novato", "Guardião da biblioteca", "Fantasma residente", "Cuidador de criaturas", "Capitão do time", "Intruso"],
  "Nave Espacial": ["Capitão", "Engenheiro de propulsão", "Cientista", "Médico de bordo", "Piloto", "Robô de manutenção", "Passageiro clandestino", "Comandante de missão"],
  "Restaurante Japonês": ["Chef executivo", "Sushiman", "Garçom", "Gerente", "Cliente VIP", "Sommelier de saquê", "Entregador", "Aprendiz de cozinha"],
  "Delegacia de Polícia": ["Delegado", "Detetive sênior", "Policial civil", "Suspeito", "Testemunha", "Advogado de defesa", "Perito criminal", "Informante"],
  "Parque de Diversões": ["Gerente geral", "Operador de montanha-russa", "Palhaço", "Segurança", "Visitante ansioso", "Vendedor de algodão-doce", "Mascote do parque", "Técnico de manutenção"],
  Cinema: ["Projecionista", "Atendente de bilheteria", "Espectador", "Segurança", "Gerente", "Crítico de cinema", "Pipoqueiro", "Diretor de produção"],
  "Quartel de Bombeiros": ["Comandante", "Bombeiro veterano", "Motorista do caminhão", "Socorrista", "Recruta", "Despachante de emergência", "Voluntário", "Mecânico"],
  "Escola de Culinária": ["Chef instrutor", "Aluno iniciante", "Aluno avançado", "Auxiliar de cozinha", "Crítico gastronômico", "Fornecedor de ingredientes", "Diretor da escola", "Camareira"],
  "Estação Espacial": ["Astronauta líder", "Engenheiro de sistemas", "Biólogo", "Físico de partículas", "Controlador de missão na Terra", "Robô assistente", "Médico", "Fotógrafo espacial"],
  "Cassino": ["Crupiê", "Segurança de piso", "Apostador veterano", "Gerente de sala", "Contador", "Garçonete", "Detetive de fraudes", "Showman"],
  "Navio de Cruzeiro": ["Capitão", "Oficial de navigação", "Animador de bordo", "Chef de restaurante", "Passageiro idoso", "Médico de bordo", "Técnico de máquinas", "Concierge"],
  "Academia de Artes Marciais": ["Sensei", "Faixa preta graduado", "Aluno iniciante", "Árbitro de competição", "Técnico esportivo", "Patrocinador", "Rival", "Comentarista"],
  "Laboratório Secreto": ["Cientista-chefe", "Assistente de pesquisa", "Cobaia voluntária", "Agente de segurança", "Hacker intruso", "Investidor", "Engenheiro de hardware", "Vigilante noturno"],
  "Circo": ["Domador de leões", "Trapezista", "Palhaço-chefe", "Mágico", "Acrobata", "Dono do circo", "Bilheteiro", "Técnico de iluminação"],
  "Delegacia Futurista": ["Detetive cibernético", "Hacker arrestado", "Robô policial", "Analista de dados", "Advogado de IA", "Informante digital", "Engenheiro forense", "Chefe de divisão"],
  "Fazenda": ["Fazendeiro", "Veterinário", "Peão", "Agrônomo", "Tratador de animais", "Colhedor sazonal", "Mecânico de equipamentos", "Visitante curioso"],
  "Estúdio de Gravação": ["Produtor musical", "Vocalista", "Guitarrista", "Engenheiro de som", "DJ", "Manager da banda", "Técnico de estúdio", "Jornalista musical"],
  "Museu de Arte": ["Curador", "Restaurador", "Guarda de segurança", "Visitante", "Guia turístico", "Mecenas", "Artista em exposição", "Crítico de arte"],
  "Mansão Assombrada": ["Fantasma antigo", "Caçador de fantasmas", "Turista corajoso", "Zelador misterioso", "Parapsicólogo", "Câmera-man de reality", "Descendente do dono", "Exorcista"],
  "Supermercado": ["Gerente de loja", "Caixa", "Repositor de estoque", "Cliente apressado", "Segurança", "Promotor de vendas", "Faxineiro", "Fiscal de preços"],
  "Teatro": ["Diretor teatral", "Ator principal", "Ator coadjuvante", "Técnico de som", "Iluminador", "Maquiador", "Figurinista", "Crítico teatral"],
  "Trem Noturno": ["Maquinista", "Revisor", "Passageiro misterioso", "Detetive particular", "Viajante dormindo", "Contraventor", "Policial ferroviário", "Garçonete do vagão-restaurante"],
  "Zoológico": ["Zookeeper", "Biólogo", "Veterinário", "Visitante com criança", "Fotógrafo de natureza", "Diretor do zoológico", "Guia educacional", "Técnico de enriquecimento ambiental"],
  "Plataforma de Petróleo": ["Engenheiro-chefe", "Mergulhador", "Operador de plataforma", "Mecânico", "Cozinheiro", "Piloto de helicóptero", "Inspetor de segurança", "Gerente de operações"],
  "Escola de Espionagem": ["Diretor da agência", "Instrutor de campo", "Agente trainee", "Especialista em disfarces", "Analista de inteligência", "Hacker da agência", "Especialista em armamentos", "Toupeira infiltrada"],
  "Praia": ["Salva-vidas", "Ambulante", "Turista", "Instrutor de surfe", "Pescador", "Jogador de vôlei de praia", "Fotógrafo", "Dono de barraca"],
  "Hospital Psiquiátrico": ["Psiquiatra", "Psicólogo", "Enfermeiro especializado", "Paciente internado", "Assistente social", "Segurança", "Terapeuta ocupacional", "Visitante"],
  "Estação Antártica": ["Glaciologista", "Meteorologista", "Médico da base", "Piloto de helicóptero", "Biólogo marinho", "Cozinheiro", "Técnico de comunicações", "Pesquisador visitante"],
};

export const QUESTIONS = [
  // Pessoais
  "Qual é o seu maior medo?",
  "Se você pudesse ser qualquer animal, qual seria?",
  "O que você faria com um milhão de reais?",
  "Qual seria a sua última refeição?",
  "O que você nunca faria por dinheiro?",
  "Qual é a coisa mais corajosa que você já fez?",
  "Se você pudesse voltar no tempo, para quando iria?",
  "O que você faria no seu último dia na Terra?",
  "Qual é a coisa que você mais se arrepende de não ter feito?",
  "Se você fosse um personagem de filme, quem seria?",
  "O que você faria se soubesse que não ia falhar?",
  "Qual seria o seu superpoder ideal?",
  "Se você pudesse morar em qualquer lugar do mundo, onde seria?",
  "O que você nunca vai esquecer na sua vida?",
  "Se você pudesse mudar uma coisa no mundo, o que mudaria?",
  "Qual é a pior decisão que você já tomou?",
  "O que te faz levantar da cama de manhã?",
  "Se você tivesse que largar tudo e recomeçar, o que faria?",
  "Qual é o seu talento escondido?",
  "O que as pessoas geralmente se surpreendem ao descobrir sobre você?",
  // Filosóficas / dilemas
  "Você prefere ser rico e infeliz ou pobre e feliz?",
  "Se pudesse ser imortal, aceitaria?",
  "Você salvaria um estranho ou seu animal de estimação?",
  "Prefere saber como vai morrer ou quando vai morrer?",
  "Se todos os seus erros fossem públicos, você viveria diferente?",
  "Você prefere ter muitos amigos superficiais ou poucos amigos de verdade?",
  "O que é mais importante: ser amado ou ser respeitado?",
  "Se pudesse apagar uma memória, apagaria qual?",
  "Você abriria mão de 5 anos de vida para ser famoso?",
  "Prefere nunca mentir ou nunca ouvir a verdade?",
  "Se você soubesse que ia morrer amanhã, o que faria hoje?",
  "Você prefere viver 100 anos medíocres ou 50 anos extraordinários?",
  "O que você faria se descobrisse que tem 1 ano de vida?",
  "Você trocaria sua identidade por uma vida completamente diferente?",
  // Situacionais divertidas
  "O que você faria se acordasse famoso?",
  "Se você fosse invisível por um dia, o que faria?",
  "O que você faria se encontrasse uma mala cheia de dinheiro?",
  "Se você tivesse que viver em uma série de TV, qual escolheria?",
  "O que você faria se pudesse falar com animais?",
  "Se você tivesse que sobreviver sozinho em uma ilha, o que levaria?",
  "O que você faria se a IA tomasse seu emprego?",
  "Se você pudesse ter qualquer empresa do mundo, qual escolheria?",
  "O que você faria se acordasse no passado com todo seu conhecimento atual?",
  "Se você fosse presidente por um dia, o que mudaria?",
  // Revelações pessoais
  "Qual é a mentira que você mais repete?",
  "Qual é a coisa mais estranha que você acredita?",
  "O que você nunca contou pra ninguém?",
  "Qual é o maior risco que você já correu?",
  "O que você faz quando ninguém está olhando?",
  "Qual é o seu maior vício?",
  "O que você tem vergonha de gostar?",
  "Qual é o seu maior orgulho pessoal?",
  "O que te deixa com inveja nos outros?",
  "Qual é a coisa mais infantil que você ainda faz?",
];

export const TWO_FACTIONS_PAIRS = [
  // Comida
  ["Pizza", "Hambúrguer"],
  ["Café", "Chá"],
  ["Chocolate ao leite", "Chocolate amargo"],
  ["Sushi", "Churrasco"],
  ["Tapioca", "Pão de queijo"],
  ["Sorvete de creme", "Sorvete de chocolate"],
  ["Brigadeiro", "Beijinho"],
  ["Lasanha", "Macarrão"],
  // Animais
  ["Gato", "Cachorro"],
  ["Leão", "Tigre"],
  ["Tubarão", "Baleia"],
  ["Águia", "Coruja"],
  // Preferências de estilo de vida
  ["Praia", "Montanha"],
  ["Verão", "Inverno"],
  ["Cidade grande", "Interior"],
  ["Dia", "Noite"],
  ["Madrugador", "Coruja noturna"],
  ["Casa", "Apartamento"],
  ["Campo", "Mar"],
  // Pop culture
  ["Batman", "Superman"],
  ["Harry Potter", "Senhor dos Anéis"],
  ["Marvel", "DC"],
  ["Star Wars", "Star Trek"],
  ["PlayStation", "Xbox"],
  ["Android", "iPhone"],
  // Personalidade / comportamento
  ["Introvertido", "Extrovertido"],
  ["Organizado", "Bagunçado"],
  ["Racional", "Emocional"],
  ["Planejador", "Improvisador"],
  ["Aventureiro", "Caseiro"],
  // Entretenimento
  ["Filme", "Série"],
  ["Cinema", "Netflix"],
  ["Livro", "Audiobook"],
  ["Rock", "Pop"],
  ["Funk", "Sertanejo"],
  ["Futebol", "Basquete"],
  ["RPG", "FPS"],
  // Histórico / mitologia
  ["Vampiro", "Lobisomem"],
  ["Fada", "Bruxa"],
  ["Robô", "Alienígena"],
  ["Ninja", "Samurai"],
  ["Viking", "Pirata"],
];

export const CATEGORIES_WITH_ITEMS: Record<string, string[]> = {
  Frutas: ["Maçã", "Banana", "Morango", "Manga", "Uva", "Abacaxi", "Melão", "Kiwi", "Melancia", "Pêssego", "Cereja", "Goiaba", "Mamão", "Coco", "Framboesa"],
  Verduras: ["Alface", "Espinafre", "Rúcula", "Couve", "Repolho", "Agrião", "Acelga", "Brócolis", "Couve-flor", "Escarola"],
  "Instrumentos Musicais": ["Violão", "Piano", "Bateria", "Trompete", "Saxofone", "Flauta", "Violino", "Contrabaixo", "Guitarra elétrica", "Clarinete", "Trombone", "Harpa", "Acordeão", "Ukulele"],
  Esportes: ["Futebol", "Basquete", "Vôlei", "Tênis", "Natação", "Boxe", "Ciclismo", "Atletismo", "Judô", "Surfe", "Escalada", "Ginástica", "Handebol", "Polo aquático", "Rugby"],
  Países: ["Brasil", "Japão", "França", "Egito", "Austrália", "Argentina", "Índia", "Canadá", "México", "Itália", "Alemanha", "China", "Rússia", "Coreia do Sul", "Portugal", "Espanha", "Noruega"],
  Profissões: ["Médico", "Engenheiro", "Professor", "Chef", "Piloto", "Astronauta", "Arquiteto", "Bombeiro", "Jornalista", "Psicólogo", "Advogado", "Dentista", "Programador", "Fotógrafo", "Veterinário"],
  Animais: ["Leão", "Golfinho", "Águia", "Cobra", "Urso", "Lobo", "Tigre", "Elefante", "Pinguim", "Panda", "Tubarão", "Gorila", "Camelo", "Flamingo", "Tartaruga"],
  "Meios de Transporte": ["Avião", "Trem", "Navio", "Submarino", "Helicóptero", "Moto", "Bicicleta", "Teleférico", "Foguete", "Barco a vela", "Bonde", "Metrô", "Dirigível"],
  "Super-Heróis": ["Batman", "Homem-Aranha", "Mulher-Maravilha", "Superman", "Flash", "Homem de Ferro", "Thor", "Capitão América", "Pantera Negra", "Doutor Estranho", "Viúva Negra", "Aquaman"],
  "Tipos de Música": ["Rock", "Pop", "Samba", "Funk", "Forró", "Sertanejo", "Jazz", "Blues", "Hip-hop", "Metal", "Classical", "Reggae", "Eletrônica", "Pagode", "K-pop"],
  Oceanos: ["Atlântico", "Pacífico", "Índico", "Ártico", "Antártico"],
  Planetas: ["Mercúrio", "Vênus", "Terra", "Marte", "Júpiter", "Saturno", "Urano", "Netuno"],
  "Tipos de Queijo": ["Mozzarella", "Parmesão", "Cheddar", "Gorgonzola", "Brie", "Gouda", "Ricota", "Prato", "Coalho", "Gruyère"],
  "Capitais do Mundo": ["Paris", "Tóquio", "Londres", "Roma", "Berlim", "Madrid", "Pequim", "Moscou", "Cairo", "Buenos Aires", "Ottawa", "Lisboa", "Amsterdã", "Seul"],
  "Tipos de Cachorro": ["Labrador", "Pastor Alemão", "Bulldog", "Golden Retriever", "Husky", "Poodle", "Shih-Tzu", "Rottweiler", "Chihuahua", "Dálmata", "Beagle", "Boxer"],
  "Personagens de Disney": ["Simba", "Elsa", "Moana", "Ariel", "Bela", "Cinderela", "Woody", "Buzz", "Nemo", "Wall-E", "Stitch", "Rapunzel"],
  "Tipos de Macarrão": ["Espaguete", "Penne", "Fusilli", "Farfalle", "Lasanha", "Tagliatelle", "Rigatoni", "Linguine", "Orzo", "Gnocchi"],
  "Monumentos Históricos": ["Torre Eiffel", "Coliseu", "Machu Picchu", "Stonehenge", "Pirâmides de Gizé", "Taj Mahal", "Muralha da China", "Cristo Redentor", "Partenon", "Angkor Wat", "Big Ben"],
  "Tipos de Dança": ["Samba", "Forró", "Tango", "Valsa", "Hip-hop", "Ballet", "Flamenco", "Zouk", "Breakdance", "Salsa", "Axé"],
  "Elementos Químicos": ["Oxigênio", "Hidrogênio", "Ouro", "Ferro", "Carbono", "Hélio", "Urânio", "Prata", "Cobre", "Mercúrio", "Chumbo"],
  "Cidades do Brasil": ["São Paulo", "Rio de Janeiro", "Salvador", "Fortaleza", "Manaus", "Curitiba", "Recife", "Belo Horizonte", "Porto Alegre", "Florianópolis", "Belém", "Brasília"],
  "Tipos de Chocolate": ["Ao leite", "Amargo", "Branco", "Ruby", "Com avelã", "Com menta", "Com laranja", "Trufado", "Com amendoim", "Diet"],
  "Jogos de Tabuleiro": ["Xadrez", "Banco Imobiliário", "Detetive", "War", "Uno", "Catan", "Ticket to Ride", "Dobble", "Codenames", "Dixit"],
};

export const MOVIES_SERIES = [
  // Filmes clássicos
  {
    title: "O Poderoso Chefão",
    year: 1972, director: "Francis Ford Coppola",
    genre: "Crime / Drama",
    cast: "Marlon Brando, Al Pacino, James Caan",
    synopsis: "O patriarca de uma família mafiosa transfere o controle de seu império para o filho relutante após ser alvejado por rivais.",
  },
  {
    title: "Matrix",
    year: 1999, director: "Lana e Lilly Wachowski",
    genre: "Ação / Ficção Científica",
    cast: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    synopsis: "Um hacker descobre que toda a realidade é uma simulação computacional e se junta à resistência contra as máquinas.",
  },
  {
    title: "Interestelar",
    year: 2014, director: "Christopher Nolan",
    genre: "Ficção Científica",
    cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    synopsis: "Com a Terra se tornando inabitável, um piloto viaja por um buraco de minhoca para encontrar um novo lar para a humanidade.",
  },
  {
    title: "A Origem",
    year: 2010, director: "Christopher Nolan",
    genre: "Ação / Ficção Científica",
    cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    synopsis: "Um ladrão especializado em roubar segredos de sonhos recebe a missão inversa: plantar uma ideia na mente de alguém.",
  },
  {
    title: "Parasita",
    year: 2019, director: "Bong Joon-ho",
    genre: "Thriller / Drama",
    cast: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
    synopsis: "Uma família pobre e desempregada infiltra-se progressivamente na vida de uma família rica com consequências imprevisíveis.",
  },
  {
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    year: 2001, director: "Peter Jackson",
    genre: "Fantasia / Aventura",
    cast: "Elijah Wood, Ian McKellen, Viggo Mortensen",
    synopsis: "Um hobbit inicia uma jornada épica para destruir um anel mágico que ameaça escravizar toda a Terra Média.",
  },
  {
    title: "Clube da Luta",
    year: 1999, director: "David Fincher",
    genre: "Drama / Thriller",
    cast: "Brad Pitt, Edward Norton, Helena Bonham Carter",
    synopsis: "Um homem insatisfeito com sua vida monótona funda um clube secreto de luta que evolui para algo muito mais perigoso.",
  },
  {
    title: "Forrest Gump",
    year: 1994, director: "Robert Zemeckis",
    genre: "Drama / Comédia",
    cast: "Tom Hanks, Robin Wright, Gary Sinise",
    synopsis: "Um homem simples do Alabama atravessa décadas de história americana simplesmente seguindo seu coração.",
  },
  {
    title: "De Volta para o Futuro",
    year: 1985, director: "Robert Zemeckis",
    genre: "Aventura / Ficção Científica",
    cast: "Michael J. Fox, Christopher Lloyd, Lea Thompson",
    synopsis: "Um adolescente é acidentalmente enviado para 1955 e precisa garantir que seus pais se apaixonem para poder voltar ao futuro.",
  },
  {
    title: "Pulp Fiction",
    year: 1994, director: "Quentin Tarantino",
    genre: "Crime / Thriller",
    cast: "John Travolta, Samuel L. Jackson, Uma Thurman",
    synopsis: "Histórias interconectadas de criminosos, filósofos de boteco e assassinos profissionais na Los Angeles underground.",
  },
  {
    title: "Vingadores: Ultimato",
    year: 2019, director: "Anthony e Joe Russo",
    genre: "Ação / Ficção Científica",
    cast: "Robert Downey Jr., Chris Evans, Scarlett Johansson",
    synopsis: "Os heróis sobreviventes se unem em uma missão desesperada para reverter o estalo de Thanos e restaurar o universo.",
  },
  {
    title: "O Labirinto do Fauno",
    year: 2006, director: "Guillermo del Toro",
    genre: "Fantasia / Drama",
    cast: "Ivana Baquero, Sergi López, Doug Jones",
    synopsis: "Na Espanha pós-guerra civil, uma menina descobre um labirinto mágico onde um fauno lhe revela ser uma princesa de um reino fantástico.",
  },
  {
    title: "Whiplash",
    year: 2014, director: "Damien Chazelle",
    genre: "Drama / Música",
    cast: "Miles Teller, J.K. Simmons, Melissa Benoist",
    synopsis: "Um jovem baterista ambicioso enfrenta um professor de música brutalmente exigente em busca da perfeição absoluta.",
  },
  {
    title: "La La Land",
    year: 2016, director: "Damien Chazelle",
    genre: "Romance / Musical",
    cast: "Ryan Gosling, Emma Stone, John Legend",
    synopsis: "Um pianista de jazz e uma atriz aspirante se apaixonam em Los Angeles enquanto perseguem seus sonhos artísticos.",
  },
  {
    title: "Coringa",
    year: 2019, director: "Todd Phillips",
    genre: "Drama / Thriller",
    cast: "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
    synopsis: "A origem do lendário vilão: um comediante fracassado e perturbado descende à loucura e se transforma no Coringa.",
  },
  {
    title: "Oppenheimer",
    year: 2023, director: "Christopher Nolan",
    genre: "Drama histórico / Thriller",
    cast: "Cillian Murphy, Emily Blunt, Matt Damon",
    synopsis: "A história do físico J. Robert Oppenheimer e o desenvolvimento da primeira bomba atômica no Projeto Manhattan.",
  },
  {
    title: "Tudo em Todo o Lugar ao Mesmo Tempo",
    year: 2022, director: "Daniel Kwan e Daniel Scheinert",
    genre: "Ficção Científica / Comédia",
    cast: "Michelle Yeoh, Ke Huy Quan, Jamie Lee Curtis",
    synopsis: "Uma imigrante chinesa descobre que pode acessar habilidades de versões paralelas de si mesma e deve salvar o multiverso.",
  },
  {
    title: "Dune: Parte 1",
    year: 2021, director: "Denis Villeneuve",
    genre: "Ficção Científica / Épico",
    cast: "Timothée Chalamet, Zendaya, Oscar Isaac",
    synopsis: "Um jovem nobre é levado ao planeta desértico Arrakis, o único lugar do universo onde se produz a especiaria mais valiosa de todas.",
  },
  {
    title: "Saltburn",
    year: 2023, director: "Emerald Fennell",
    genre: "Thriller / Drama",
    cast: "Barry Keoghan, Jacob Elordi, Rosamund Pike",
    synopsis: "Um estudante de Oxford de origem humilde se torna obcecado por um colega aristocrata e passa o verão em sua mansão extravagante.",
  },
  {
    title: "Pobres Criaturas",
    year: 2023, director: "Yorgos Lanthimos",
    genre: "Fantasia / Drama",
    cast: "Emma Stone, Mark Ruffalo, Willem Dafoe",
    synopsis: "Uma jovem ressuscitada por um cientista excêntrico foge com um advogado libertino em uma aventura que a transforma completamente.",
  },
  // Séries
  {
    title: "Breaking Bad",
    year: 2008, director: "Vince Gilligan",
    genre: "Drama / Crime",
    cast: "Bryan Cranston, Aaron Paul, Anna Gunn",
    synopsis: "Um professor de química com câncer terminal se une a um ex-aluno para produzir metanfetamina e acaba se tornando um temido criminoso.",
  },
  {
    title: "Stranger Things",
    year: 2016, director: "Matt e Ross Duffer",
    genre: "Ficção Científica / Terror",
    cast: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
    synopsis: "Quando um menino desaparece, sua cidade descobre experimentos secretos do governo, forças sobrenaturais e uma menina com poderes.",
  },
  {
    title: "Game of Thrones",
    year: 2011, director: "David Benioff e D.B. Weiss",
    genre: "Fantasia / Drama",
    cast: "Emilia Clarke, Kit Harington, Peter Dinklage",
    synopsis: "Nobres famílias guerreiam pelo controle dos Sete Reinos enquanto uma ameaça sobrenatural avança pelo Norte.",
  },
  {
    title: "The Last of Us",
    year: 2023, director: "Craig Mazin e Neil Druckmann",
    genre: "Drama / Ficção Científica",
    cast: "Pedro Pascal, Bella Ramsey, Anna Torv",
    synopsis: "Um sobrevivente endurecido e uma adolescente imune percorrem um Estados Unidos devastado por um fungo que transforma humanos.",
  },
  {
    title: "Black Mirror",
    year: 2011, director: "Charlie Brooker",
    genre: "Ficção Científica / Thriller",
    cast: "Bryce Dallas Howard, Jon Hamm, Hayley Atwell",
    synopsis: "Antologia de histórias perturbadoras sobre o lado sombrio da tecnologia e seus efeitos na sociedade moderna.",
  },
  {
    title: "Chernobyl",
    year: 2019, director: "Johan Renck",
    genre: "Drama histórico / Thriller",
    cast: "Jared Harris, Stellan Skarsgård, Emily Watson",
    synopsis: "A reconstrução detalhada do desastre nuclear de Chernobyl em 1986 e os esforços desesperados para conter a catástrofe.",
  },
  {
    title: "Squid Game",
    year: 2021, director: "Hwang Dong-hyuk",
    genre: "Thriller / Drama",
    cast: "Lee Jung-jae, Park Hae-soo, HoYeon Jung",
    synopsis: "Centenas de pessoas endividadas participam de um torneio mortal de jogos infantis em troca de um prêmio milionário.",
  },
  {
    title: "Dark",
    year: 2017, director: "Baran bo Odar e Jantje Friese",
    genre: "Ficção Científica / Thriller",
    cast: "Louis Hofmann, Oliver Masucci, Karoline Eichhorn",
    synopsis: "O desaparecimento de crianças em uma cidade alemã expõe uma conspiração de viagem no tempo ligando quatro famílias ao longo de séculos.",
  },
  {
    title: "The Bear",
    year: 2022, director: "Christopher Storer",
    genre: "Drama / Comédia",
    cast: "Jeremy Allen White, Ebon Moss-Bachrach, Ayo Edebiri",
    synopsis: "Um chef premiado abandona restaurantes estrelados para tocar a lanchonete caótica da família após a morte do irmão.",
  },
  {
    title: "Succession",
    year: 2018, director: "Jesse Armstrong",
    genre: "Drama",
    cast: "Brian Cox, Jeremy Strong, Sarah Snook",
    synopsis: "Os filhos de um magnata da mídia disputam ferozmente pelo controle do império familiar enquanto o patriarca se recusa a soltar o poder.",
  },
  {
    title: "Severance",
    year: 2022, director: "Ben Stiller e Aoife McArdle",
    genre: "Thriller / Ficção Científica",
    cast: "Adam Scott, Patricia Arquette, John Turturro",
    synopsis: "Funcionários de uma empresa misteriosa passam por um procedimento que separa completamente suas memórias profissionais das pessoais.",
  },
  {
    title: "True Detective",
    year: 2014, director: "Cary Joji Fukunaga",
    genre: "Crime / Drama",
    cast: "Matthew McConaughey, Woody Harrelson, Michelle Monaghan",
    synopsis: "Dois detetives de personalidades opostas investigam uma série de assassinatos rituais ao longo de 17 anos no Louisiana.",
  },
  {
    title: "Peaky Blinders",
    year: 2013, director: "Steven Knight",
    genre: "Drama / Crime",
    cast: "Cillian Murphy, Helen McCrory, Tom Hardy",
    synopsis: "Na Birmingham pós-Primeira Guerra Mundial, uma família de gângsteres liderada por um veterano ambicioso constrói um império criminoso.",
  },
  {
    title: "Euphoria",
    year: 2019, director: "Sam Levinson",
    genre: "Drama",
    cast: "Zendaya, Hunter Schafer, Jacob Elordi",
    synopsis: "Um grupo de adolescentes navega por drogas, identidade, sexualidade e violência em uma cidade americana contemporânea.",
  },
  {
    title: "The Witcher",
    year: 2019, director: "Lauren Schmidt Hissrich",
    genre: "Fantasia / Ação",
    cast: "Henry Cavill, Freya Allan, Anya Chalotra",
    synopsis: "Um caçador de monstros mutante, uma feiticeira poderosa e uma princesa com um destino extraordinário se cruzam em um mundo fantástico.",
  },
];

// Hints por palavra — formato: "está relacionado a [X]"
const WORD_HINTS: Record<string, string> = {
  // Objetos cotidianos
  "Geladeira": "eletrodomésticos usados na cozinha",
  "Guarda-chuva": "acessórios usados em dias de chuva",
  "Mochila": "bolsas e acessórios para carregar coisas",
  "Colchão": "móveis e itens para dormir",
  "Ventilador": "eletrodomésticos que controlam temperatura",
  "Escova de dente": "higiene pessoal e cuidados bucais",
  "Garrafa térmica": "utensílios para conservar bebidas",
  "Travesseiro": "itens de cama e conforto para dormir",
  "Relógio": "acessórios para medir ou decorar",
  "Óculos": "acessórios para visão ou proteção",
  "Carteira": "acessórios pessoais para guardar documentos",
  "Chave": "objetos usados para abrir ou travar coisas",
  "Caneta": "material escolar e de escritório",
  "Tesoura": "ferramentas de corte e material escolar",
  "Espelho": "objetos domésticos de reflexo",
  "Vela": "objetos de iluminação ou decoração",
  "Corda": "ferramentas e equipamentos de amarração",
  "Régua": "material escolar e de desenho técnico",
  "Mapa": "ferramentas de navegação e orientação",
  "Bússola": "instrumentos de orientação e exploração",
  // Animais
  "Elefante": "animais selvagens de grande porte",
  "Golfinho": "animais marinhos inteligentes",
  "Pinguim": "aves de clima frio que não voam",
  "Cobra": "répteis peçonhentos ou não",
  "Águia": "aves de rapina e voo alto",
  "Tartaruga": "répteis de casco e vida longa",
  "Polvo": "animais marinhos com muitos tentáculos",
  "Camelo": "animais adaptados ao deserto",
  "Gorila": "primatas de grande porte da selva",
  "Flamingo": "aves cor-de-rosa de pernas longas",
  "Urso polar": "animais carnívoros do Ártico",
  "Tubarão": "predadores marinhos de grande porte",
  "Panda": "animais ameaçados e muito famosos em zoológicos",
  "Leão": "felinos predadores da savana africana",
  "Tigre": "felinos listrados de grande porte",
  "Baleia": "mamíferos marinhos gigantes",
  "Coruja": "aves noturnas símbolo de sabedoria",
  "Raposa": "canídeos astutos das florestas",
  "Lobo": "canídeos selvagens que vivem em alcateia",
  "Macaco": "primatas ágeis das florestas tropicais",
  // Alimentos
  "Pizza": "pratos redondos da culinária italiana",
  "Sorvete": "sobremesas geladas e cremosas",
  "Chocolate": "doces feitos de cacau",
  "Hambúrguer": "lanches de fast food com carne",
  "Sushi": "pratos da culinária japonesa com peixe cru",
  "Pastel": "salgados fritos de massa fina",
  "Coxinha": "salgados fritos típicos do Brasil",
  "Macarrão": "massas da culinária italiana",
  "Queijo": "laticínios fermentados e envelhecidos",
  "Mel": "alimentos naturais produzidos por abelhas",
  "Pipoca": "lanches de milho estourado",
  "Tapioca": "pratos típicos brasileiros feitos de mandioca",
  "Bolo": "doces assados para festas e comemorações",
  "Brigadeiro": "doces brasileiros de chocolate condensado",
  "Mousse": "sobremesas aeradas e cremosas",
  "Churros": "doces fritos de massa crocante",
  "Croissant": "pães amanteigados da confeitaria francesa",
  "Ramen": "sopas japonesas de macarrão",
  "Lasanha": "massas em camadas da culinária italiana",
  "Paçoca": "doces brasileiros feitos de amendoim",
  // Tecnologia
  "Computador": "equipamentos eletrônicos de processamento",
  "Celular": "dispositivos móveis de comunicação",
  "Fone de ouvido": "acessórios eletrônicos para ouvir áudio",
  "Câmera": "equipamentos de fotografia e filmagem",
  "Drone": "aeronaves controladas remotamente",
  "Impressora": "equipamentos de escritório para imprimir",
  "Teclado": "periféricos de computador ou instrumentos musicais",
  "Mouse": "periféricos de informática",
  "Tablet": "dispositivos eletrônicos touchscreen portáteis",
  "Microfone": "equipamentos de captação de som",
  "Alto-falante": "equipamentos que reproduzem som",
  "Carregador": "acessórios para recarregar eletrônicos",
  // Natureza
  "Vulcão": "formações geológicas com lava e magma",
  "Cachoeira": "quedas d'água na natureza",
  "Deserto": "biomas secos com pouca chuva e muita areia",
  "Iceberg": "blocos de gelo gigantes que flutuam no oceano",
  "Floresta": "biomas de vegetação densa com muitas árvores",
  "Coral": "estruturas naturais subaquáticas coloridas",
  "Furacão": "tempestades tropicais gigantes e destrutivas",
  "Aurora boreal": "fenômenos luminosos no céu noturno polar",
  "Gêiser": "fontes naturais de água quente que espiram",
  "Caverna": "formações subterrâneas naturais ou artificiais",
  "Penhasco": "formações rochosas altas e íngremes",
  "Lago": "corpos d'água interiores cercados de terra",
  "Nevoeiro": "fenômenos climáticos de névoa densa",
  "Avalanche": "desastres naturais de neve ou pedras deslizando",
  "Redemoinho": "movimentos circulares de água ou vento",
  "Relâmpago": "descargas elétricas durante tempestades",
  "Arco-íris": "fenômenos ópticos coloridos após a chuva",
  // Transporte
  "Submarino": "veículos militares ou científicos que navegam submersos",
  "Foguete": "veículos que viajam para o espaço",
  "Helicóptero": "aeronaves com hélices que pousam verticalmente",
  "Navio": "embarcações grandes que cruzam oceanos",
  "Trem bala": "trens de altíssima velocidade",
  "Teleférico": "transporte suspenso usado em montanhas",
  "Moto aquática": "veículos motorizados para esportes aquáticos",
  "Planador": "aeronaves sem motor que planam no vento",
  "Zeppelin": "aeronaves históricas em formato de balão gigante",
  "Bicicleta": "veículos de pedal para transporte ou esporte",
  "Trator": "máquinas pesadas usadas na agricultura",
  "Ambulância": "veículos de emergência para atendimento médico",
  // Lugares
  "Biblioteca": "locais públicos cheios de livros",
  "Castelo": "construções medievais de pedra com torres",
  "Farol": "estruturas litorâneas que guiam embarcações",
  "Pirâmide": "monumentos históricos do Egito antigo",
  "Iglu": "construções de gelo usadas em regiões árticas",
  "Bunker": "abrigos subterrâneos de proteção militar",
  "Observatório": "instalações científicas para estudar o céu",
  "Labirinto": "estruturas com caminhos confusos e enganosos",
  "Cemitério": "locais de sepultamento e memória",
  "Aquário": "instalações com tanques de animais marinhos",
  "Museu": "locais culturais que guardam objetos históricos",
  "Circo": "espetáculos itinerantes com acrobacias e palhaços",
  // Esportes e lazer
  "Paraquedas": "esportes radicais de queda livre do céu",
  "Skate": "esportes urbanos com prancha e rodas",
  "Escalada": "esportes de aventura em rochas ou paredes",
  "Mergulho": "esportes aquáticos abaixo da superfície",
  "Arco e flecha": "esportes ou armas históricas de precisão",
  "Xadrez": "jogos de tabuleiro e estratégia mental",
  "Boliche": "esportes de arremessar bola em pinos",
  "Golfe": "esportes de campo com tacos e buracos",
  "Surfe": "esportes aquáticos em ondas do mar",
  "Parkour": "esportes urbanos de acrobacias em obstáculos",
  // Objetos temáticos
  "Bisturi": "instrumentos médicos usados em cirurgias",
  "Martelo": "ferramentas de construção e carpintaria",
  "Pincel": "utensílios artísticos para pintura",
  "Violino": "instrumentos musicais de cordas",
  "Troféu": "prêmios de competições e conquistas",
  "Diploma": "documentos de formação acadêmica",
  "Passaporte": "documentos oficiais para viagens internacionais",
  "Bilhete": "documentos ou ingressos para transporte e eventos",
  "Moeda": "dinheiro físico e objetos de coleção",
  // Conceitos abstratos
  "Segredo": "conceitos de mistério e informação oculta",
  "Sonho": "experiências da mente durante o sono ou desejos",
  "Memória": "conceitos de lembrança e passado",
  "Silêncio": "conceitos de ausência de som",
  "Sombra": "fenômenos de luz e escuridão",
  "Eco": "fenômenos sonoros de reverberação",
};

// Hints por pergunta — tema geral sem revelar a pergunta
const QUESTION_HINTS: Record<string, string> = {
  "Qual é o seu maior medo?": "medos e fobias pessoais",
  "Se você pudesse ser qualquer animal, qual seria?": "escolhas hipotéticas envolvendo animais",
  "O que você faria com um milhão de reais?": "o que faria com muito dinheiro",
  "Qual seria a sua última refeição?": "comida e preferências gastronômicas",
  "O que você nunca faria por dinheiro?": "limites pessoais e valores morais",
  "Qual é a coisa mais corajosa que você já fez?": "coragem e atitudes marcantes do passado",
  "Se você pudesse voltar no tempo, para quando iria?": "viagem no tempo e momentos do passado",
  "O que você faria no seu último dia na Terra?": "prioridades de vida e o que mais importa",
  "Qual é a coisa que você mais se arrepende de não ter feito?": "arrependimentos e oportunidades perdidas",
  "Se você fosse um personagem de filme, quem seria?": "identificação com personagens fictícios",
  "O que você faria se soubesse que não ia falhar?": "sonhos e ambições sem medo do fracasso",
  "Qual seria o seu superpoder ideal?": "superpoderes e habilidades fantásticas",
  "Se você pudesse morar em qualquer lugar do mundo, onde seria?": "lugares do mundo e estilo de vida ideal",
  "O que você nunca vai esquecer na sua vida?": "memórias marcantes e inesquecíveis",
  "Se você pudesse mudar uma coisa no mundo, o que mudaria?": "mudanças no mundo e valores sociais",
  "Qual é a pior decisão que você já tomou?": "erros e más decisões do passado",
  "O que te faz levantar da cama de manhã?": "motivações e o que te move na vida",
  "Se você tivesse que largar tudo e recomeçar, o que faria?": "recomeçar a vida do zero",
  "Qual é o seu talento escondido?": "habilidades secretas e talentos pouco conhecidos",
  "O que as pessoas geralmente se surpreendem ao descobrir sobre você?": "características surpreendentes da personalidade",
  "Você prefere ser rico e infeliz ou pobre e feliz?": "dilemas entre dinheiro e felicidade",
  "Se pudesse ser imortal, aceitaria?": "imortalidade e o sentido da vida",
  "Você salvaria um estranho ou seu animal de estimação?": "dilemas morais difíceis de escolher",
  "Prefere saber como vai morrer ou quando vai morrer?": "conhecimento sobre o próprio destino",
  "Se todos os seus erros fossem públicos, você viveria diferente?": "julgamento alheio e autenticidade",
  "Você prefere ter muitos amigos superficiais ou poucos amigos de verdade?": "amizade e qualidade dos relacionamentos",
  "O que é mais importante: ser amado ou ser respeitado?": "amor versus respeito nas relações",
  "Se pudesse apagar uma memória, apagaria qual?": "memórias dolorosas que gostariam de esquecer",
  "Você abriria mão de 5 anos de vida para ser famoso?": "fama e o preço que valeria pagar",
  "Prefere nunca mentir ou nunca ouvir a verdade?": "honestidade e mentiras na vida",
  "Se você soubesse que ia morrer amanhã, o que faria hoje?": "prioridades diante da morte iminente",
  "Você prefere viver 100 anos medíocres ou 50 anos extraordinários?": "qualidade versus quantidade de vida",
  "O que você faria se descobrisse que tem 1 ano de vida?": "o que faria sabendo que vai morrer em breve",
  "Você trocaria sua identidade por uma vida completamente diferente?": "identidade pessoal e reinvenção",
  "O que você faria se acordasse famoso?": "fama repentina e como lidar com ela",
  "Se você fosse invisível por um dia, o que faria?": "invisibilidade e escolhas sem ser visto",
  "O que você faria se encontrasse uma mala cheia de dinheiro?": "dinheiro achado e dilemas éticos",
  "Se você tivesse que viver em uma série de TV, qual escolheria?": "séries favoritas e mundos fictícios",
  "O que você faria se pudesse falar com animais?": "comunicação com animais e o que perguntaria",
  "Se você tivesse que sobreviver sozinho em uma ilha, o que levaria?": "sobrevivência e itens essenciais numa ilha",
  "O que você faria se a IA tomasse seu emprego?": "futuro do trabalho e inteligência artificial",
  "Se você pudesse ter qualquer empresa do mundo, qual escolheria?": "negócios e empresas mais desejadas",
  "O que você faria se acordasse no passado com todo seu conhecimento atual?": "voltar ao passado sabendo o que sabe hoje",
  "Se você fosse presidente por um dia, o que mudaria?": "política e mudanças que faria no poder",
  "Qual é a mentira que você mais repete?": "mentiras frequentes e autoengano",
  "Qual é a coisa mais estranha que você acredita?": "crenças incomuns ou conspiratórias",
  "O que você nunca contou pra ninguém?": "segredos profundos nunca revelados",
  "Qual é o maior risco que você já correu?": "riscos e aventuras do passado",
  "O que você faz quando ninguém está olhando?": "comportamentos privados e segredos cotidianos",
  "Qual é o seu maior vício?": "vícios e hábitos difíceis de largar",
  "O que você tem vergonha de gostar?": "gostos secretos e guilty pleasures",
  "Qual é o seu maior orgulho pessoal?": "conquistas e realizações pessoais",
  "O que te deixa com inveja nos outros?": "inveja e o que admira nos outros",
  "Qual é a coisa mais infantil que você ainda faz?": "hábitos infantis que ainda mantém",
};

// Hints por par de facções — descreve o tema sem revelar as palavras
const FACTION_PAIR_HINTS: Record<string, string> = {
  "Pizza|Hambúrguer": "dois tipos de comida muito populares",
  "Café|Chá": "duas bebidas quentes muito consumidas",
  "Chocolate ao leite|Chocolate amargo": "dois tipos do mesmo alimento doce",
  "Sushi|Churrasco": "duas culinárias e estilos de comer muito diferentes",
  "Tapioca|Pão de queijo": "dois lanches tradicionais brasileiros",
  "Sorvete de creme|Sorvete de chocolate": "dois sabores de uma sobremesa gelada",
  "Brigadeiro|Beijinho": "dois doces clássicos de festas brasileiras",
  "Lasanha|Macarrão": "dois tipos de massa da culinária italiana",
  "Gato|Cachorro": "dois animais domésticos muito populares",
  "Leão|Tigre": "dois grandes felinos predadores",
  "Tubarão|Baleia": "dois animais marinhos de grande porte",
  "Águia|Coruja": "duas aves conhecidas e muito simbólicas",
  "Praia|Montanha": "dois destinos naturais de férias",
  "Verão|Inverno": "duas estações opostas do ano",
  "Cidade grande|Interior": "dois estilos de vida e moradia",
  "Dia|Noite": "dois períodos opostos de 24 horas",
  "Madrugador|Coruja noturna": "dois hábitos opostos de sono e rotina",
  "Casa|Apartamento": "dois tipos de moradia urbana",
  "Campo|Mar": "dois ambientes naturais de lazer",
  "Batman|Superman": "dois super-heróis icônicos da DC Comics",
  "Harry Potter|Senhor dos Anéis": "duas franquias épicas de fantasia",
  "Marvel|DC": "duas grandes editoras e universos de super-heróis",
  "Star Wars|Star Trek": "duas franquias gigantes de ficção científica espacial",
  "PlayStation|Xbox": "dois consoles rivais de videogame",
  "Android|iPhone": "dois sistemas operacionais de celular rivais",
  "Introvertido|Extrovertido": "dois tipos opostos de personalidade social",
  "Organizado|Bagunçado": "dois estilos opostos de organização",
  "Racional|Emocional": "duas formas opostas de tomar decisões",
  "Planejador|Improvisador": "dois estilos opostos de lidar com o futuro",
  "Aventureiro|Caseiro": "dois estilos de vida opostos",
  "Filme|Série": "dois formatos de entretenimento audiovisual",
  "Cinema|Netflix": "dois jeitos de assistir filmes e séries",
  "Livro|Audiobook": "dois formatos de consumir literatura",
  "Rock|Pop": "dois gêneros musicais muito populares",
  "Funk|Sertanejo": "dois gêneros musicais brasileiros muito populares",
  "Futebol|Basquete": "dois esportes coletivos muito populares",
  "RPG|FPS": "dois gêneros de videogame muito jogados",
  "Vampiro|Lobisomem": "duas criaturas sobrenaturais clássicas do folclore",
  "Fada|Bruxa": "dois personagens femininos de contos de fada",
  "Robô|Alienígena": "dois seres fictícios da ficção científica",
  "Ninja|Samurai": "dois guerreiros icônicos da cultura japonesa",
  "Viking|Pirata": "dois guerreiros aventureiros históricos",
};

export function getHintForMode(mode: GameMode, secretInfo: unknown): string {
  switch (mode) {
    case "secret-word": {
      const info = secretInfo as { word: string };
      const hint = WORD_HINTS[info.word];
      return hint
        ? `A palavra é algo relacionado a ${hint}`
        : `A palavra começa com "${info.word[0].toUpperCase()}" e tem ${info.word.length} letras`;
    }
    case "location-role": {
      const info = secretInfo as { location: string };
      return `O local é ${getLocationHint(info.location)}`;
    }
    case "question": {
      const info = secretInfo as { question: string };
      const hint = QUESTION_HINTS[info.question];
      return hint
        ? `A pergunta é sobre ${hint}`
        : `A pergunta é sobre preferências ou experiências pessoais`;
    }
    case "two-factions": {
      const info = secretInfo as { words: string[] };
      const key = `${info.words[0]}|${info.words[1]}`;
      const hint = FACTION_PAIR_HINTS[key];
      return hint
        ? `Os times têm palavras de tema: ${hint}`
        : `Existem dois times com palavras relacionadas entre si`;
    }
    case "category-item": {
      const info = secretInfo as { category: string };
      return `Todos os itens do jogo pertencem à categoria "${info.category}"`;
    }
    case "movie-series": {
      const info = secretInfo as { genre: string; year: number };
      return `A obra é do gênero ${info.genre}${info.year ? `, lançada em ${info.year}` : ""}`;
    }
    default:
      return "Observe com atenção as respostas dos outros jogadores!";
  }
}

function getLocationHint(location: string): string {
  const hints: Record<string, string> = {
    Hospital: "um local de saúde onde médicos e pacientes convivem",
    Aeroporto: "um terminal onde aviões chegam e partem com passageiros",
    "Escola de Magia": "uma instituição de ensino com magia e feitiços",
    "Nave Espacial": "um veículo que viaja pelo espaço sideral",
    "Restaurante Japonês": "um restaurante especializado em culinária japonesa",
    "Delegacia de Polícia": "um órgão de segurança pública com policiais e suspeitos",
    "Parque de Diversões": "um parque de lazer com brinquedos e atrações",
    Cinema: "um local de entretenimento para assistir filmes",
    "Quartel de Bombeiros": "uma base de bombeiros prontos para emergências",
    "Escola de Culinária": "uma escola onde se aprende a cozinhar profissionalmente",
    "Estação Espacial": "uma estrutura habitável em órbita no espaço",
    Cassino: "um local de jogos de azar e apostas",
    "Navio de Cruzeiro": "um navio gigante de viagens e lazer pelo mar",
    "Academia de Artes Marciais": "um local de treinamento de luta e disciplina",
    "Laboratório Secreto": "uma instalação sigilosa de pesquisa científica",
    Circo: "um espetáculo com acrobacias, palhaços e animais",
    "Delegacia Futurista": "uma delegacia policial com tecnologia avançada",
    Fazenda: "uma propriedade rural com animais e plantações",
    "Estúdio de Gravação": "um local profissional para gravar músicas",
    "Museu de Arte": "um espaço cultural com obras de arte expostas",
    "Mansão Assombrada": "uma mansão misteriosa com fantasmas e segredos",
    Supermercado: "um grande mercado onde se compra alimentos e produtos",
    Teatro: "um espaço de apresentações ao vivo com atores",
    "Trem Noturno": "um trem em viagem longa durante a noite",
    Zoológico: "um parque onde animais selvagens ficam em cativeiro",
    "Plataforma de Petróleo": "uma estrutura no mar para extrair petróleo",
    "Escola de Espionagem": "uma agência secreta que treina espiões",
    Praia: "um litoral com areia, mar e sol para lazer",
    "Hospital Psiquiátrico": "uma clínica especializada em saúde mental",
    "Estação Antártica": "uma base científica no polo sul gelado",
  };
  return hints[location] ?? "um local público com várias pessoas e funções";
}
